### ISSUE TITLE
Starboard Mega-Issue

### ISSUE THREAD

**Issue by andrewj-brown** [UQComputingSociety/uqcsbot-discord#158]
Making a mega-issue for all the things wrong with starboard.

- [ ] re-order DB interactions per PR #123
- [ ] add starboard msg-deletion handler per PR #123 
- [ ] remove BlacklistedMessageException in favour of a StarboardMessagePair object per PR #123
- [ ] add static types to starboard per PR #123
- [ ] fix starboard post rendering when the user has left the server (top_role is not defined)
- [ ] add backup emoji for when/if :starhaj: is removed from the server (nitro moment)
- [ ] write comprehensive documentation & wiki-page for everything starboard does
